### ISSUE TITLE
[PE-D][Tester E] Attendance on the same day

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W09-4/tp#134]
![image.png](https://raw.githubusercontent.com/zupey/ped/main/files/ad74e604-d34e-401b-b379-7bec4228f9c1.png)

Can add attendance for the same person on the same day.  If this is a feature, then how can the user differentiate the different lessons that is held on the same day?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zupey/ped#2

**Comment by jwdavis0200** [comment]
Just create warning message for duplicate attendance
