### ISSUE TITLE
[PE-D][Tester A] Duplicates for Grade Progress are allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W09-4/tp#148]
![image.png](https://raw.githubusercontent.com/Hoodineee/ped/main/files/610cc894-5178-4789-b7ab-594cc1deae0b.png)

Duplicates for Grade Progress are allowed which could confuse the user.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Hoodineee/ped#3

**Comment by AshiqurRah** [comment]
Will be including this in the UG
