### ISSUE TITLE
[PE-D][Tester E] User unable to tell which mode he is in

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W09-4/tp#165]
![image.png](https://raw.githubusercontent.com/zupey/ped/main/files/84c0a348-e8ee-4858-b194-e3a57af13d89.png)

After adding session, the user cannot tell which mode (list mode or view mode), thus wasting time when the command requires to be in the other mode

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zupey/ped#5

**Comment by cfyjoanna** [comment]
not really sure how we would add this at this stage since we can't add features/change GUI

**Comment by phyliciachristel** [comment]
@cfyjoanna so true im closing this
