### ISSUE TITLE
[PE-D][Tester C] Phone number does not allows usage of country code.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W09-4/tp#176]
# In UG
![image.png](https://raw.githubusercontent.com/Tan-Jia-Rong/ped/main/files/57c6a4c1-8f06-49f2-918e-9c1fcfa391f5.png)

# In application
![image.png](https://raw.githubusercontent.com/Tan-Jia-Rong/ped/main/files/35495a98-513a-4732-809e-d2ad88716ca1.png)

It is listed as a functionality bug as it is not explicitly stated that country code are not allowed. Hence, users may find that the adding of phone number does not work as intended.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Tan-Jia-Rong/ped#14

**Comment by cfyjoanna** [comment]
not a bug imo response already states that phone numbers should only contain numbers. working as intended

country code issue already brought up as feature flaw in another issue

@ anyone can close if u agree
